apiVersion: v2
name: capa-karpenter-taint-remover
version: 1.0.2
description: "CAPA karpenter taint remover"
appVersion: 1.0.1-dev
home: "https://github.com/giantswarm/capa-karpenter-taint-remover"
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  io.giantswarm.application.team: phoenix
